version: 2

builds:
  - main: .
    binary: tyle
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

brews:
  - repository:
      owner: atkntepe
      name: homebrew-tap
    homepage: https://github.com/atkntepe/tyle
    description: Layout manager for Ghostty terminal
    license: MIT
    install: |
      bin.install "tyle"
